name = "CatlabHyperGraphs"
uuid = "e71bc8c3-5cab-4e5e-b669-39cf24ff44f4"
authors = ["anand jain <anandj@uchicago.edu>"]
version = "0.1.0"

[deps]
AlgebraicRewriting = "725a01d3-f174-5bbd-84e1-b9417bad95d9"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
